name: test
load_from_checkpoint: null
test_model: True

seed: 5721 # Random seed

trainer:
  epochs: 50
  val_interval: 0.5
  log_steps: 50
  accumulate_grad_batches: 2
  eval_metrics: val_loss

callbacks:
  checkpointing:
    checkpoint_freq: 1
    save_top_k: 2
  roc_curve: True

defaults:
 - logger: wandb
 - datamodule: md_datamodule_invariant
 - model: gcn_misato_feats
 - _self_
